# Generated by Django 4.2.4 on 2023-09-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_post', '0002_remove_post_like_post_like_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_by',
            new_name='like',
        ),
    ]
